# Dokploy Configuration for Crashed Car Sales App
version: '1.0'

project:
  name: crashed-car-sales-app
  description: "Web application for selling crashed cars to dealers and scrapyards"

services:
  # Backend Service
  backend:
    name: crashed-car-sales-backend
    type: application
    source:
      type: git
      repository: https://github.com/your-username/crashed-car-sales-app.git
      branch: main
      path: backend
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      replicas: 2
      resources:
        memory: 1Gi
        cpu: 500m
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8080:8080"
    health_check:
      path: /api/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    name: crashed-car-sales-frontend
    type: application
    source:
      type: git
      repository: https://github.com/your-username/crashed-car-sales-app.git
      branch: main
      path: frontend
    build:
      dockerfile: Dockerfile
      context: .
    deploy:
      replicas: 2
      resources:
        memory: 512Mi
        cpu: 250m
    environment:
      NEXT_PUBLIC_API_URL: https://api.yourdomain.com/api
      NEXT_PUBLIC_CDN_URL: ${CDN_BASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Database Service (PostgreSQL on Neo.tech)
  database:
    name: crashed-car-sales-db
    type: postgres
    version: "15"
    storage: 20Gi
    environment:
      POSTGRES_DB: crashed_car_sales
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    backup:
      enabled: true
      schedule: "0 2 * * *" # Daily at 2 AM
      retention: 7 # Keep 7 days of backups

  # Redis Cache
  redis:
    name: crashed-car-sales-redis
    type: redis
    version: "7"
    storage: 1Gi
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

# Load Balancer Configuration
load_balancer:
  enabled: true
  ssl:
    enabled: true
    certificate_type: letsencrypt
  domains:
    - yourdomain.com
    - www.yourdomain.com
  routes:
    - path: /api/*
      service: backend
      port: 8080
    - path: /*
      service: frontend
      port: 3000

# Monitoring
monitoring:
  enabled: true
  metrics:
    - service: backend
      path: /api/actuator/prometheus
    - service: frontend
      path: /api/metrics

# Environment Variables (to be set in Dokploy dashboard)
environment_variables:
  - DATABASE_URL
  - DATABASE_USERNAME
  - DATABASE_PASSWORD
  - REDIS_HOST
  - REDIS_PORT
  - REDIS_PASSWORD
  - JWT_SECRET
  - S3_BUCKET
  - S3_ACCESS_KEY
  - S3_SECRET_KEY
  - CDN_BASE_URL
  - MAIL_USERNAME
  - MAIL_PASSWORD