version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crashed-car-sales-postgres
    environment:
      POSTGRES_DB: crashed_car_sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - crashed-car-sales-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: crashed-car-sales-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crashed-car-sales-network

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: crashed-car-sales-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - crashed-car-sales-network

  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: crashed-car-sales-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://postgres:5432/crashed_car_sales
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin123
      S3_BUCKET: crashed-car-sales
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - crashed-car-sales-network

  # Frontend Application
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: crashed-car-sales-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
      NEXT_PUBLIC_CDN_URL: http://localhost:9000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - crashed-car-sales-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  crashed-car-sales-network:
    driver: bridge