services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crashed-car-sales-postgres
    environment:
      POSTGRES_DB: crashed_car_sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Puerto 5433 para PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - crashed-car-sales-network

  # Redis Cache - COMMENTED OUT
  # redis:
  #   image: redis:7-alpine
  #   container_name: crashed-car-sales-redis
  #   ports:
  #     - "6381:6379"  # Puerto 6381 para Redis
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - crashed-car-sales-network

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: crashed-car-sales-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - crashed-car-sales-network

  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: crashed-car-sales-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://postgres:5432/crashed_car_sales
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin123
      S3_BUCKET: crashed-car-sales
    ports:
      - "8081:8080"  # Puerto 8081 para Spring Boot
    depends_on:
      - postgres
      # - redis
      - minio
    networks:
      - crashed-car-sales-network

  # Frontend Application
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: crashed-car-sales-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8081/api  # Actualizado para usar puerto 8081
      NEXT_PUBLIC_CDN_URL: http://localhost:9000
    ports:
      - "3001:3000"  # Puerto 3001 para Next.js
    depends_on:
      - backend
    networks:
      - crashed-car-sales-network

volumes:
  postgres_data:
  # redis_data:
  minio_data:

networks:
  crashed-car-sales-network:
    driver: bridge